restic/__init__.py
restic/restic_test.py

It doesn't make sense to allow clients to turn this off because most responses are assumed to be JSON when we parse them.

Change the --json flag to be added unconditionally

---

docs/index.md

Github Pages automatically inserts one.

Remove top-level header in API docs

---

docs/index.md
restic/internal/forget.py
restic/internal/forget_test.py

Moving forward with this project, it might be worth considering to dynamically allow all possible parameters for restic instead of statically implement each and everyone. But that will be a lot of refactoring and breaking changes :)

Implement more flags for 'restic forget'

---

docs/index.md

We were inconsistent about whether arg descriptions end in a period in the API docs, so this change makes them consistently omit the period.

Remove trailing periods for args in docs

---

docs/index.md
e2e/test.py
restic/__init__.py
restic/internal/key.py
restic/internal/key_test.py

This PR implements the 'key' command:
```
$ restic key --help
The "key" command manages keys (passwords) for accessing the repository.
EXIT STATUS
===========
Exit status is 0 if the command was successful, and non-zero if there was any error.
Usage:
restic key [flags] [list|add|remove|passwd] [ID]
Flags:
-h, --help                     help for key
--host string              the hostname for new keys
--new-password-file file   file from which to read the new password
--user string              the username for new keys
Global Flags:
--cacert file                file to load root certificates from (default: use system certificates)
--cache-dir directory        set the cache directory. (default: use system default cache directory)
--cleanup-cache              auto remove old cache …
```

Implement 'key' command

---

e2e/test.py

Declare the encoding at file open time rather than on each individual write.

Handle text encoding consistently in e2e tests

---

docs/index.md
e2e/test.py
restic/internal/copy.py
restic/internal/copy_test.py
restic/internal/init.py
restic/internal/init_test.py

Hi there,
due to https://github.com/restic/restic/pull/3742 --repo2 is deprecated.
I've added full support for --from-repo and --from-password-file. This should be completely backward compatible and repo2 still works (but give it a good test anyway).
Using repo2 will now print a warning like with restic:
I've added additional FIXME notes where you can remove code in your next major (breaking) release.
Unfortunately I was not successful in adjusting the e2e tests.
Changing this:
caused this:
It looks like something is flaky (or not cleaned up afterwards for another run). Or my dev setup is broken.

Replace --repo2 with --from-repo

---

e2e/test.py

restic 0.15.0 doesn't provide a stable order in the key list anymore.
Fixes #123.

Ensure we remove the unused key

---

.pylintrc
restic/internal/forget.py
restic/internal/forget_test.py

Resolves #139
During commit I got the following PyLint warning:
`restic/internal/forget.py:7:0: R0912: Too many branches (13/12) (too-many-branches)`
Therefore I changed `max-branches` from 12 to 13 in `.pylintrc`.
This is my very first PR so I hope everything is fine?! ;-)
Furthermore I am very new into Python programming, usually doing .NET stuff.
When will this change be available via pip after merging into your repo?
Many thanks in advance!
Michael

Implement support for `forget` with tags and host options

---

restic/internal/forget_test.py

It's a little unexpected for there to be a tag with a comma within it, so I'm simplifying to two standard-looking tags.

Simplify tags in forget test

---

docs/index.md
restic/internal/forget_test.py

Added tests for multiple tags:
- `test_forget_with_multiple_tags_with_or_relation`: Testing OR relation of tags
- `test_forget_with_multiple_tags_with_and_relation`: Testing AND relation of tags
- Incl. reference to restic documentation
Updated documentation:
- Added new parameters `tags`/`host` in forget

forget: Added tests for multiple tags and updated documentation

---

docs/index.md
restic/internal/stats.py
restic/internal/stats_test.py

Changes:
- `restic/internal/stats.py`: Added tags and host options
- `restic/internal/stats_test.py`: Added tests for new options
- `docs/index.md`: Added new options to documentation
Many thanks for your efforts!

stats: Added support for tags and host options

---

restic/internal/snapshots_test.py

When there are no snapshots, restic returns an empty list, not an empty dict.

Fix unit tests for snapshot()

---

docs/index.md
restic/internal/snapshots.py
restic/internal/snapshots_test.py

Added functionality to specify restic's `--tag` argument when using the `snapshots()` command. Added associated unit test.

Added 'tags' argument to snapshot command

---

restic/internal/restore.py
restic/internal/restore_test.py

Add the `--exclude` parameter to the restore command.
Resolves: #159

Support exclude flag for restore command

---

.circleci/config.yml

This fixes an issue with twine version 4.0.2, which depends on the latest version of importlib-metadata (>= 3.6).
Consequently, it is impacted by the breaking changes introduced in importlib-metadata version 8.0.0.
This issue has been resolved in https://github.com/pypa/twine/pull/1124.

Upgrade twine to resolve issue with importlib-metadata

---

.circleci/config.yml
docs/index.md
restic/internal/snapshots.py
restic/internal/snapshots_test.py

Added functionality to specify restic's --path and --host arguments when using the snapshots() command. Added associated unit test.

Added 'tags' and 'host' arguments to snapshots command

---

docs/index.md
restic/internal/init.py
restic/internal/init_test.py

The newer versions of restic use a new repository format with new features. In legacy environments it may be useful to support both version of repository formats.

add support to set repository_version if init restic repository

---

CONTRIBUTING.md
docs/index.md
restic/internal/restore.py
restic/internal/restore_test.py

This PR will actually support multiple `exclude` patterns for the `restore` operation. Before, only **one** exclude pattern can be provided, now, similarly to the `rewrite` API, multiple exclude patterns can be provided as a list.

feat: support multiple exclude pattern for restore operation

---

docs/index.md
restic/internal/backup.py
restic/internal/backup_test.py

This PR adds an `files_from` parameter to the backup command. `files_from` takes, as `exclude_files`, a list of files as an argument. This allows to specify one (or multiple) file that contains a file list. 
It will call restic with the `--files-from` option. 
In addition the following changes were necessary: 
- Changing `paths` to an optional argument with default None. This allows to call backup with include_files, only. 
- Ensure that either `paths` or `files_from_files` (or both) are specified and not None. Raise `ValueError` in case both are None.
- Refactoring command extension with list into helper function. circlci:build was failing with too many if clauses in function.

Add files_from parameter to backup command
